javafx:
  title: VCF Analyzer
default:
  folder:
    vcf: ./src/test/resources/vcf
    order: ./src/test/resources/order
    out: ./src/test/resources/out
mapping:
  metabolizerCodes:
    Ultrarapid Metabolizer: LA10315-2 	 
    Rapid Metabolizer: LA25390-8 	 
    Normal Metabolizer: LA25391-6 	 
    Intermediate Metabolizer: LA10317-8 	 
    Poor Metabolizer: LA9657-3